# Generated by Django 4.2.4 on 2023-08-16 00:11

from django.db import migrations, models
import django.db.models.deletion
import dogs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('breed', models.CharField(max_length=255)),
                ('dob', models.DateField(verbose_name='Birthdate')),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('weight', models.IntegerField()),
                ('dog_friendly', models.BooleanField()),
                ('cat_friendly', models.BooleanField()),
                ('child_friendly', models.BooleanField()),
                ('house_broken', models.BooleanField()),
                ('profile_pic', models.ImageField(upload_to=dogs.models.get_dir, verbose_name='Profile Picture')),
                ('description', models.TextField()),
                ('adopted', models.BooleanField()),
                ('notice', models.CharField(blank=True, max_length=255, null=True)),
                ('hidden', models.BooleanField()),
                ('bonded_pair', models.ManyToManyField(blank=True, to='dogs.dog')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=dogs.models.get_dir)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.dog')),
            ],
        ),
    ]
