# Generated by Django 4.2.4 on 2023-08-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateField(verbose_name='Event Date')),
                ('time', models.TimeField(verbose_name='Time')),
            ],
        ),
    ]
